### ISSUE TITLE
Battery for Lock Devices

### ISSUE THREAD

**Issue by jvmahon** [jrhubott/homebridge-homeseer#6]
Is it possible to add a battery reference for Lock devices so that HomeKit can report when a lock's battery is going dead?

**Comment by AlanSmithe** [comment]
What happens when you add 

"batteryRef":REF_ID,                // Optional - HomeSeer device reference for the sensor battery level
"batteryThreshold":15,          // Optional - If sensor battery level is below this value, the HomeKit LowBattery characteristic is set to 1. Default is 10

to your lock config?

**Comment by jvmahon** [comment]
adding the batteryRef option is currently ignored for locks, so I assume the HomeBridge code needs to be enhanced to support it. I've been looking at the code, but don't understand it well enough to do it myself.

**Comment by AlanSmithe** [comment]
I don't know if jrhubott still supports this plugin. The last message from him on the Homeseer forum was on november 2016.

**Comment by jvmahon** [comment]
Resolution - Unlike services used for other devices such as contact switches, the  lock mechanism service doesn't directly support battery status. Need to add a second service (the battery service) to the Lock accessory which may require a different approach to configuring the accessory as there would need to be both a primary and a secondary service for the accessory.
